/* VAMONOS TENNIS — dictionnaire d'interface, anglais.
   Clé = texte français source. Chargé seulement si la langue est l'anglais. */
window.__DICO = Object.assign(window.__DICO || {}, {

/* ── accueil ── */
"home.tag":"A living tour of 1,150 players. A 46-week rolling ranking. Matches played game by game.<br><b>From age 16 to retirement, one week at a time.</b>",
"COMMENCER UNE CARRIÈRE":"START A CAREER",
"DEUX FAÇONS DE VIVRE LA MÊME CARRIÈRE":"TWO WAYS TO LIVE THE SAME CAREER",
"home.deux":"<b>⚡ Express</b> — you set a direction for the year, the tour handles the rest, and you only take over for the matches that truly matter. A whole career in one evening.<br><br><b>🎾 Full career</b> — all 46 weeks, one by one: the tournament, the training, the rest weeks, the lessons you give to pay for the next flight. Every match is played game by game, with your tactics, your freshness and your nerves.<br><br>Same world, same engine, same ranking — you pick the pace at creation. And either way, <b>every season</b> you must defend last year's points, pay your staff, and watch seven body zones wear down.",
"home.soutien":"<b>Vamonos Tennis is free, with no account and no intrusive ads.</b> This partnership is what pays for the server and the domain. If you enjoy the game and you're of age, using this link is the simplest way to support it — it costs you nothing extra.",
"REPRENDRE":"RESUME","ans":"yrs","mondial":"in the world","semaine":"week",
"Semaine":"Week","Calendrier":"Schedule","Travail":"Training","Équipe":"Team",
"Classement":"Rankings","Progrès":"Progress","Profil":"Profile",

/* ── création ── */
"AVANT DE COMMENCER":"BEFORE WE START",
"Comment vous appelle-t-on ?":"What should we call you?",
"Ce pseudo accompagnera vos carrières. Vous pourrez le changer plus tard.":"This name will follow your careers. You can change it later.",
"Votre pseudo":"Your name",
"CONTINUER":"CONTINUE",
"Aucun compte, aucun mot de passe, aucune adresse e-mail. Le jeu retient seulement ce pseudo et le déroulé de vos parties.":"No account, no password, no email. The game only keeps this name and how your careers unfold.",
"VOTRE NATION":"YOUR NATION",
"Elle oriente vos surfaces de prédilection et votre notoriété.":"It shapes your preferred surfaces and your early fame.",
"VOTRE CIRCUIT":"YOUR TOUR",
"Sur quel circuit allez-vous écrire votre histoire ?":"On which tour will you write your story?",
"Circuit masculin":"Men's tour",
"Grands Chelems en trois sets gagnants. Des matchs qui peuvent durer cinq heures.":"Grand Slams are best of five. Matches can last five hours.",
"Circuit féminin":"Women's tour",
"Tableaux en deux sets gagnants. Un circuit plus ouvert, où tout peut basculer en une saison.":"Best-of-three draws. A more open tour, where everything can change in one season.",
"VOTRE STYLE DE JEU":"YOUR PLAYING STYLE",
"Il détermine vos attributs clés, vos surfaces et votre plafond.":"It sets your key attributes, your surfaces and your ceiling.",
"VOTRE FORMATION":"YOUR BACKGROUND",
"D'où venez-vous, et avec quoi arrivez-vous chez les pros ?":"Where do you come from, and what do you bring to the pros?",
"VOTRE HYGIÈNE DE VIE":"YOUR LIFESTYLE",
"Onze mois de circuit par an. Comment tenez-vous debout ?":"Eleven months on tour every year. How do you stay standing?",
"VOTRE RYTHME":"YOUR PACE",
"Vous pourrez toujours changer d'avis en cours de carrière.":"You can always change your mind mid-career.",
"Carrière express":"Express career",
"Carrière complète":"Full career",
"Une saison se décide en un plan. Le circuit s'occupe du reste, et vous ne reprenez la main que sur les matchs qui comptent.":"A season comes down to one plan. The tour handles the rest, and you only take over for the matches that matter.",
"Une carrière complète en dix à quinze minutes.":"A whole career in ten to fifteen minutes.",
"Semaine après semaine. Vous composez votre calendrier, vous choisissez chaque bloc de travail, vous jouez vos matchs jeu par jeu.":"Week after week. You build your schedule, pick every training block, and play your matches game by game.",
"Plusieurs heures. C'est le simulateur intégral.":"Several hours. The full simulator.",
"CONSTRUCTION DU CIRCUIT":"BUILDING THE TOUR",
"1 150 joueurs, 900 tournois, une saison entière jouée à blanc pour que le classement mondial soit réel avant votre arrivée…":"1,150 players, 900 tournaments, one full season simulated so the world ranking is real before you arrive…",

/* ── semaine / travail ── */
"SEMAINE":"WEEK",
"DISPUTER LE TOURNOI":"PLAY THE TOURNAMENT",
"Renoncer et travailler cette semaine":"Skip it and train this week",
"AVANCE RAPIDE":"FAST FORWARD",
"PASSER LA SEMAINE EN RÉÉDUCATION":"SPEND THE WEEK IN REHAB",
"PASSER PLUSIEURS SEMAINES":"SKIP SEVERAL WEEKS",
"ÉTAT DU CORPS":"BODY CONDITION",
"CHOISIR LE TRAVAIL DE LA SEMAINE":"CHOOSE THIS WEEK'S TRAINING",

/* ── express ── */
"SAISON":"SEASON","ANS":"YRS","EN COURS":"IN PROGRESS","Semaine":"Week",
"Votre plan pour l'année":"Your plan for the year",
"Vous fixez une ligne, le circuit s'occupe du reste.":"You set a direction; the tour handles the rest.",
"OÙ JOUER CETTE ANNÉE":"WHERE TO PLAY THIS YEAR",
"QUOI TRAVAILLER":"WHAT TO WORK ON",
"LANCER LA SAISON":"START THE SEASON",
"CHANGER MON ÉQUIPE":"CHANGE MY TEAM",
"VOIR MA PROGRESSION":"VIEW MY PROGRESS",
"PARTAGER MA SAISON":"SHARE MY SEASON",
"LES MOMENTS DE LA SAISON":"MOMENTS OF THE SEASON",
"FIN DE CARRIÈRE ?":"END OF THE ROAD?",
"RACCROCHER LA RAQUETTE":"HANG UP THE RACQUET",
"BILAN":"W–L","TITRES":"TITLES","POINTS":"POINTS","GAINS":"PRIZE MONEY",
"Passer en carrière complète":"Switch to full career",
"Passer en carrière express":"Switch to express career",

/* ── tournoi / match ── */
"ENTRER SUR LE COURT":"WALK ON COURT",
"Exempté de ce tour":"Bye this round",
"PASSER AU TOUR SUIVANT":"ADVANCE TO NEXT ROUND",
"TERMINER LA SEMAINE":"FINISH THE WEEK",
"VAINQUEUR DU TOURNOI":"TOURNAMENT CHAMPION",
"VOTRE PLAN DE JEU":"YOUR GAME PLAN",
"VOTRE PARCOURS":"YOUR RUN",
"VICTOIRE — CONTINUER":"VICTORY — CONTINUE",
"DÉFAITE — CONTINUER":"DEFEAT — CONTINUE",
"POINT SUIVANT QUI COMPTE":"NEXT BIG POINT",
"JEU SUIVANT":"NEXT GAME",
"JOUER LE SET":"PLAY THE SET",
"SIMULER LE RESTE DU MATCH":"SIMULATE THE REST",
"3 sets gagnants":"best of five",
"2 sets gagnants":"best of three",

/* ── fin de carrière / partage ── */
"PARTAGER CETTE CARRIÈRE":"SHARE THIS CAREER",
"NOUVELLE CARRIÈRE":"NEW CAREER",
"MENU PRINCIPAL":"MAIN MENU",
"PALMARÈS":"HONOURS",
"SAISON PAR SAISON":"SEASON BY SEASON",
"NOUVEAUX BADGES":"NEW BADGES",
"CE QUI SERA ENVOYÉ":"WHAT WILL BE SENT",
"PARTAGER":"SHARE",
"COPIER LE TEXTE":"COPY TEXT",
"TÉLÉCHARGER L'IMAGE":"DOWNLOAD IMAGE",
"ENVOYER VERS":"SEND TO",
/* ── départ rapide ── */
"DÉPART RAPIDE":"QUICK START",
"Le jeu tire un joueur pour vous et lance une saison express. Vous jouez dans dix secondes.":"The game rolls a player for you and starts an express season. You'll be playing in ten seconds.",
"CRÉER MON JOUEUR MOI-MÊME":"CREATE MY OWN PLAYER",
"VOTRE JOUEUR":"YOUR PLAYER",
"Talent":"Talent",
"Plan":"Plan",
"Travail":"Training",
"Le circuit va dérouler votre première saison. Vous reprendrez la main sur les matchs qui comptent — et vous pourrez tout régler ensuite, du plan à l'équipe.":"The tour will run your first season. You'll take over for the matches that matter — and you can adjust everything afterwards, from the plan to your team.",
"C'EST PARTI":"LET'S GO",
"Je préfère choisir mon plan":"I'd rather pick my plan",
"APERÇU DE L'IMAGE":"IMAGE PREVIEW"
});
