/* VAMONOS TENNIS — diccionario de interfaz, español.
   Clé = texte français source. Chargé seulement si la langue est l'espagnol. */
window.__DICO = Object.assign(window.__DICO || {}, {

/* ── accueil ── */
"home.tag":"Un circuito vivo de 1.150 jugadores. Un ranking móvil de 46 semanas. Partidos jugados juego a juego.<br><b>De tus 16 años a la retirada, semana a semana.</b>",
"COMMENCER UNE CARRIÈRE":"EMPEZAR UNA CARRERA",
"DEUX FAÇONS DE VIVRE LA MÊME CARRIÈRE":"DOS FORMAS DE VIVIR LA MISMA CARRERA",
"home.deux":"<b>⚡ Exprés</b> — fijas una línea para el año, el circuito se ocupa del resto, y solo tomas el mando en los partidos que de verdad importan. Una carrera entera en una tarde.<br><br><b>🎾 Carrera completa</b> — las 46 semanas una a una: el torneo, el entrenamiento, el descanso, las clases que das para pagar el próximo vuelo. Cada partido se juega juego a juego, con tu táctica, tu frescura y tus nervios.<br><br>Mismo mundo, mismo motor, mismo ranking — el ritmo se elige al crear. Y en ambos casos, <b>cada temporada</b> hay que defender los puntos del año pasado, pagar al equipo y vigilar siete zonas del cuerpo que se desgastan.",
"home.soutien":"<b>Vamonos Tennis es gratis, sin cuenta y sin publicidad intrusiva.</b> Este patrocinio es lo que paga el servidor y el dominio. Si el juego te gusta y eres mayor de edad, pasar por este enlace es la forma más sencilla de apoyarlo — no te cuesta nada más.",
"REPRENDRE":"CONTINUAR","ans":"años","mondial":"del mundo","semaine":"semana",
"Semaine":"Semana","Calendrier":"Calendario","Travail":"Entreno","Équipe":"Equipo",
"Classement":"Ranking","Progrès":"Progreso","Profil":"Perfil",

/* ── création ── */
"AVANT DE COMMENCER":"ANTES DE EMPEZAR",
"Comment vous appelle-t-on ?":"¿Cómo te llamamos?",
"Ce pseudo accompagnera vos carrières. Vous pourrez le changer plus tard.":"Este nombre acompañará tus carreras. Podrás cambiarlo más adelante.",
"Votre pseudo":"Tu nombre",
"CONTINUER":"CONTINUAR",
"Aucun compte, aucun mot de passe, aucune adresse e-mail. Le jeu retient seulement ce pseudo et le déroulé de vos parties.":"Sin cuenta, sin contraseña, sin correo. El juego solo guarda este nombre y el desarrollo de tus partidas.",
"VOTRE NATION":"TU PAÍS",
"Elle oriente vos surfaces de prédilection et votre notoriété.":"Orienta tus superficies preferidas y tu fama inicial.",
"VOTRE CIRCUIT":"TU CIRCUITO",
"Sur quel circuit allez-vous écrire votre histoire ?":"¿En qué circuito vas a escribir tu historia?",
"Circuit masculin":"Circuito masculino",
"Grands Chelems en trois sets gagnants. Des matchs qui peuvent durer cinq heures.":"Grand Slams al mejor de cinco sets. Partidos que pueden durar cinco horas.",
"Circuit féminin":"Circuito femenino",
"Tableaux en deux sets gagnants. Un circuit plus ouvert, où tout peut basculer en une saison.":"Cuadros al mejor de tres. Un circuito más abierto, donde todo puede cambiar en una temporada.",
"VOTRE STYLE DE JEU":"TU ESTILO DE JUEGO",
"Il détermine vos attributs clés, vos surfaces et votre plafond.":"Determina tus atributos clave, tus superficies y tu techo.",
"VOTRE FORMATION":"TU FORMACIÓN",
"D'où venez-vous, et avec quoi arrivez-vous chez les pros ?":"¿De dónde vienes, y con qué llegas al circuito profesional?",
"VOTRE HYGIÈNE DE VIE":"TU ESTILO DE VIDA",
"Onze mois de circuit par an. Comment tenez-vous debout ?":"Once meses de gira al año. ¿Cómo te mantienes en pie?",
"VOTRE RYTHME":"TU RITMO",
"Vous pourrez toujours changer d'avis en cours de carrière.":"Siempre podrás cambiar de opinión durante la carrera.",
"Carrière express":"Carrera exprés",
"Carrière complète":"Carrera completa",
"Une saison se décide en un plan. Le circuit s'occupe du reste, et vous ne reprenez la main que sur les matchs qui comptent.":"Una temporada se decide en un plan. El circuito se ocupa del resto, y solo tomas el mando en los partidos que importan.",
"Une carrière complète en dix à quinze minutes.":"Una carrera entera en diez o quince minutos.",
"Semaine après semaine. Vous composez votre calendrier, vous choisissez chaque bloc de travail, vous jouez vos matchs jeu par jeu.":"Semana a semana. Compones tu calendario, eliges cada bloque de trabajo y juegas tus partidos juego a juego.",
"Plusieurs heures. C'est le simulateur intégral.":"Varias horas. El simulador íntegro.",
"CONSTRUCTION DU CIRCUIT":"CONSTRUYENDO EL CIRCUITO",
"1 150 joueurs, 900 tournois, une saison entière jouée à blanc pour que le classement mondial soit réel avant votre arrivée…":"1.150 jugadores, 900 torneos, una temporada entera simulada para que el ranking mundial sea real antes de tu llegada…",

/* ── semaine / travail ── */
"SEMAINE":"SEMANA",
"DISPUTER LE TOURNOI":"DISPUTAR EL TORNEO",
"Renoncer et travailler cette semaine":"Renunciar y entrenar esta semana",
"AVANCE RAPIDE":"AVANCE RÁPIDO",
"PASSER LA SEMAINE EN RÉÉDUCATION":"PASAR LA SEMANA EN REHABILITACIÓN",
"PASSER PLUSIEURS SEMAINES":"SALTAR VARIAS SEMANAS",
"ÉTAT DU CORPS":"ESTADO DEL CUERPO",
"CHOISIR LE TRAVAIL DE LA SEMAINE":"ELEGIR EL TRABAJO DE LA SEMANA",

/* ── express ── */
"SAISON":"TEMPORADA","ANS":"AÑOS","EN COURS":"EN CURSO","Semaine":"Semana",
"Votre plan pour l'année":"Tu plan para el año",
"Vous fixez une ligne, le circuit s'occupe du reste.":"Fijas una línea; el circuito se ocupa del resto.",
"OÙ JOUER CETTE ANNÉE":"DÓNDE JUGAR ESTE AÑO",
"QUOI TRAVAILLER":"QUÉ TRABAJAR",
"LANCER LA SAISON":"EMPEZAR LA TEMPORADA",
"CHANGER MON ÉQUIPE":"CAMBIAR MI EQUIPO",
"VOIR MA PROGRESSION":"VER MI PROGRESO",
"PARTAGER MA SAISON":"COMPARTIR MI TEMPORADA",
"LES MOMENTS DE LA SAISON":"LOS MOMENTOS DE LA TEMPORADA",
"FIN DE CARRIÈRE ?":"¿FIN DE CARRERA?",
"RACCROCHER LA RAQUETTE":"COLGAR LA RAQUETA",
"BILAN":"V–D","TITRES":"TÍTULOS","POINTS":"PUNTOS","GAINS":"PREMIOS",
"Passer en carrière complète":"Pasar a carrera completa",
"Passer en carrière express":"Pasar a carrera exprés",

/* ── tournoi / match ── */
"ENTRER SUR LE COURT":"SALTAR A LA PISTA",
"Exempté de ce tour":"Exento de esta ronda",
"PASSER AU TOUR SUIVANT":"PASAR A LA SIGUIENTE RONDA",
"TERMINER LA SEMAINE":"TERMINAR LA SEMANA",
"VAINQUEUR DU TOURNOI":"CAMPEÓN DEL TORNEO",
"VOTRE PLAN DE JEU":"TU PLAN DE PARTIDO",
"VOTRE PARCOURS":"TU RECORRIDO",
"VICTOIRE — CONTINUER":"VICTORIA — CONTINUAR",
"DÉFAITE — CONTINUER":"DERROTA — CONTINUAR",
"POINT SUIVANT QUI COMPTE":"SIGUIENTE PUNTO CLAVE",
"JEU SUIVANT":"SIGUIENTE JUEGO",
"JOUER LE SET":"JUGAR EL SET",
"SIMULER LE RESTE DU MATCH":"SIMULAR EL RESTO",
"3 sets gagnants":"al mejor de cinco",
"2 sets gagnants":"al mejor de tres",

/* ── fin de carrière / partage ── */
"PARTAGER CETTE CARRIÈRE":"COMPARTIR ESTA CARRERA",
"NOUVELLE CARRIÈRE":"NUEVA CARRERA",
"MENU PRINCIPAL":"MENÚ PRINCIPAL",
"PALMARÈS":"PALMARÉS",
"SAISON PAR SAISON":"TEMPORADA A TEMPORADA",
"NOUVEAUX BADGES":"NUEVAS INSIGNIAS",
"CE QUI SERA ENVOYÉ":"LO QUE SE ENVIARÁ",
"PARTAGER":"COMPARTIR",
"COPIER LE TEXTE":"COPIAR TEXTO",
"TÉLÉCHARGER L'IMAGE":"DESCARGAR IMAGEN",
"ENVOYER VERS":"ENVIAR A",
"APERÇU DE L'IMAGE":"VISTA PREVIA"
});
